# Generated by Django 4.2 on 2023-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeQuestsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('ai_generated', models.BooleanField(default=False)),
                ('correct_output', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('V', 'Very Hard'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('R', 'Realy Hard')], default='M', max_length=1)),
            ],
        ),
    ]
