# Generated by Django 4.2 on 2023-05-05 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeQuestsApp', '0008_alter_match_second_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='second_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
