# Generated by Django 4.2.1 on 2023-07-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeQuestsApp', '0009_alter_match_second_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
