# Generated by Django 4.2.1 on 2023-07-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeQuestsApp', '0010_course_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
