# Generated by Django 4.2.1 on 2023-07-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeQuestsApp', '0012_solution_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='match',
        ),
    ]
