# Generated by Django 4.2.1 on 2023-07-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeQuestsApp', '0014_solution_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='output',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
